name: Publish Blog CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    # - name: Install npm dependencies
    #   run: npm install
    # - name: Run build task
    #   run: npm run build --prod
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.2.3
      with:
          BRANCH: gh-pages
          FOLDER: docs/.vuepress/dist
          BUILD_SCRIPT: npm install && npm run build --prod
      