name: Publish Blog CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install npm dependencies
      run: npm install
    - name: Run build task
      run: npm run build --prod
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.5.9
      with:
          ACCESS_TOKEN: ${{ secrets.SSH_PRIVATE_KEY }}
          REPOSITORY_NAME: nextdoing/blog
          BRANCH: gh-pages
          FOLDER: docs/.vuepress/dist
      